In [7]:
import torch

In [8]:
x = torch.Tensor([5, 3])
y = torch.Tensor([5, 3])

In [9]:
print(x * y)

tensor([25.,  9.])


In [11]:
x = torch.zeros([2,5])

In [12]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [13]:
x.shape

torch.Size([2, 5])

In [14]:
y = torch.rand([2,5])

In [15]:
print(y)

tensor([[0.6608, 0.7191, 0.5165, 0.1467, 0.4556],
        [0.2318, 0.2232, 0.3952, 0.8366, 0.8905]])


In [16]:
print(x*y)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [22]:
print(y.view([1,10]))

tensor([[0.6608, 0.7191, 0.5165, 0.1467, 0.4556, 0.2318, 0.2232, 0.3952, 0.8366,
         0.8905]])
